import { Type } from "@google/genai";
import { z } from "zod";
import type { UsageAnalysis } from "@/src/lib/types";

export const ANALYSIS_FACET_NAMES = [
  "has_celebrity",
  "has_human_face",
  "features_female",
  "features_male",
  "has_screenshot_ui",
  "has_text_overlay",
  "has_chart_or_graph",
  "has_logo_or_watermark",
  "caption_brief",
  "scene_description",
  "ocr_text",
  "primary_subjects",
  "secondary_subjects",
  "visible_objects",
  "setting_context",
  "action_or_event",
  "video_music",
  "video_sound",
  "video_dialogue",
  "video_action",
  "primary_emotion",
  "emotional_tone",
  "conveys",
  "user_intent",
  "rhetorical_role",
  "text_media_relationship",
  "metaphor",
  "humor_mechanism",
  "cultural_reference",
  "reference_entity",
  "reference_source",
  "reference_plot_context",
  "analogy_target",
  "analogy_scope",
  "meme_format",
  "persuasion_strategy",
  "brand_signals",
  "trend_signal",
  "reuse_pattern",
  "why_it_works",
  "audience_takeaway",
  "search_keywords",
  "confidence_notes",
  "usage_notes"
] as const;

export type AnalysisFacetName = (typeof ANALYSIS_FACET_NAMES)[number];

export const ANALYSIS_FACET_VALUE_TYPES = {
  has_celebrity: "boolean",
  has_human_face: "boolean",
  features_female: "boolean",
  features_male: "boolean",
  has_screenshot_ui: "boolean",
  has_text_overlay: "boolean",
  has_chart_or_graph: "boolean",
  has_logo_or_watermark: "boolean",
  caption_brief: "string",
  scene_description: "string",
  ocr_text: "string",
  primary_subjects: "string[]",
  secondary_subjects: "string[]",
  visible_objects: "string[]",
  setting_context: "string",
  action_or_event: "string",
  video_music: "string",
  video_sound: "string",
  video_dialogue: "string",
  video_action: "string",
  primary_emotion: "string",
  emotional_tone: "string",
  conveys: "string",
  user_intent: "string",
  rhetorical_role: "string",
  text_media_relationship: "string",
  metaphor: "string",
  humor_mechanism: "string",
  cultural_reference: "string",
  reference_entity: "string",
  reference_source: "string",
  reference_plot_context: "string",
  analogy_target: "string",
  analogy_scope: "string",
  meme_format: "string",
  persuasion_strategy: "string",
  brand_signals: "string[]",
  trend_signal: "string",
  reuse_pattern: "string",
  why_it_works: "string",
  audience_takeaway: "string",
  search_keywords: "string[]",
  confidence_notes: "string",
  usage_notes: "string"
} as const satisfies Record<AnalysisFacetName, "boolean" | "string" | "string[]">;

export const ANALYSIS_FACET_DESCRIPTIONS = {
  has_celebrity: "Whether the media clearly contains a widely recognizable public figure or celebrity.",
  has_human_face: "Whether one or more human faces are visibly present in the media.",
  features_female: "Whether a prominent depicted person appears female-presenting.",
  features_male: "Whether a prominent depicted person appears male-presenting.",
  has_screenshot_ui: "Whether the media is mainly a screenshot of software, a webpage, a terminal, a dashboard, or app UI.",
  has_text_overlay: "Whether prominent text is rendered inside the media itself.",
  has_chart_or_graph: "Whether a chart, graph, or similar diagram is a major visual element.",
  has_logo_or_watermark: "Whether a visible logo, brand mark, or watermark appears in the media.",
  caption_brief: "A literal one-sentence caption of the media.",
  scene_description: "A fuller visual description of what is happening in the media.",
  ocr_text: "Text visible inside the media, typically extracted through OCR.",
  primary_subjects: "The main people, entities, or subjects shown in the media.",
  secondary_subjects: "Secondary people, entities, or supporting subjects visible in the media.",
  visible_objects: "Concrete objects that are visibly present in the media.",
  setting_context: "The setting, environment, or situational context depicted in the media.",
  action_or_event: "The main action, event, or behavior shown in the media.",
  video_music: "For video, the music present and the mood or pacing it creates.",
  video_sound: "For video, the notable audio present such as dialogue, ambience, or sound effects.",
  video_dialogue: "For video, the spoken words or paraphrased dialogue that are audible in the clip.",
  video_action: "For video, the temporal sequence of visible actions or shot progression.",
  primary_emotion: "The single dominant emotion conveyed most strongly by the media.",
  emotional_tone: "The broader emotional or stylistic tone communicated by the media.",
  conveys: "The social or emotional message the post communicates through the media.",
  user_intent: "Why the author likely chose this exact media in this tweet.",
  rhetorical_role: "The rhetorical job the media performs, such as reaction, evidence, explainer, or meme.",
  text_media_relationship: "How the tweet text and media reinforce, contrast, or reframe each other.",
  metaphor: "The implied analogy or symbolic pairing created by the media and tweet text.",
  humor_mechanism: "If the post is humorous, the comedic mechanism that makes it work.",
  cultural_reference: "Any materially relevant external reference such as a show, character, meme, event, or public figure.",
  reference_entity: "The most specific named entity involved in a cultural or historical reference.",
  reference_source: "The broader source or canon the reference comes from.",
  reference_plot_context: "The specific plotline, role, business behavior, or context that makes the reference relevant.",
  analogy_target: "The real-world target that the reference or analogy is mapping onto.",
  analogy_scope: "The level at which the analogy operates, such as personal, company, market, or geopolitical.",
  meme_format: "The recognizable meme or reusable content format represented by the media.",
  persuasion_strategy: "The persuasion tactic or influence strategy the media supports.",
  brand_signals: "Brand, company, or product signals conveyed by the media.",
  trend_signal: "Why this media could travel, spread, or get reused.",
  reuse_pattern: "How other posters might reuse the same asset or media archetype.",
  why_it_works: "Why the media-text pairing is legible and effective for the likely audience.",
  audience_takeaway: "The main conclusion or feeling the audience is meant to leave with.",
  search_keywords: "Short retrieval-oriented keywords for exact and fuzzy search.",
  confidence_notes: "Notes about uncertainty, ambiguity, or confidence in the analysis.",
  usage_notes: "Additional notes specific to this tweet-media usage."
} as const satisfies Record<AnalysisFacetName, string>;

export const ANALYSIS_FACET_CATALOG = ANALYSIS_FACET_NAMES.map((name) => ({
  name,
  valueType: ANALYSIS_FACET_VALUE_TYPES[name],
  description: ANALYSIS_FACET_DESCRIPTIONS[name]
}));

export const usageAnalysisSchema = z.object({
  usageId: z.string(),
  tweetId: z.string().nullable(),
  mediaIndex: z.number().int().nonnegative(),
  mediaKind: z.enum(["image", "video", "video_hls", "video_blob"]),
  status: z.enum(["pending", "complete"]),
  has_celebrity: z.boolean().nullable(),
  has_human_face: z.boolean().nullable(),
  features_female: z.boolean().nullable(),
  features_male: z.boolean().nullable(),
  has_screenshot_ui: z.boolean().nullable(),
  has_text_overlay: z.boolean().nullable(),
  has_chart_or_graph: z.boolean().nullable(),
  has_logo_or_watermark: z.boolean().nullable(),
  caption_brief: z.string().nullable(),
  scene_description: z.string().nullable(),
  ocr_text: z.string().nullable(),
  primary_subjects: z.array(z.string()),
  secondary_subjects: z.array(z.string()),
  visible_objects: z.array(z.string()),
  setting_context: z.string().nullable(),
  action_or_event: z.string().nullable(),
  video_music: z.string().nullable(),
  video_sound: z.string().nullable(),
  video_dialogue: z.string().nullable(),
  video_action: z.string().nullable(),
  primary_emotion: z.string().nullable(),
  emotional_tone: z.string().nullable(),
  conveys: z.string().nullable(),
  user_intent: z.string().nullable(),
  rhetorical_role: z.string().nullable(),
  text_media_relationship: z.string().nullable(),
  metaphor: z.string().nullable(),
  humor_mechanism: z.string().nullable(),
  cultural_reference: z.string().nullable(),
  reference_entity: z.string().nullable(),
  reference_source: z.string().nullable(),
  reference_plot_context: z.string().nullable(),
  analogy_target: z.string().nullable(),
  analogy_scope: z.string().nullable(),
  meme_format: z.string().nullable(),
  persuasion_strategy: z.string().nullable(),
  brand_signals: z.array(z.string()),
  trend_signal: z.string().nullable(),
  reuse_pattern: z.string().nullable(),
  why_it_works: z.string().nullable(),
  audience_takeaway: z.string().nullable(),
  search_keywords: z.array(z.string()),
  confidence_notes: z.string().nullable(),
  usage_notes: z.string().nullable()
});

export const usageAnalysisJsonSchema = {
  type: Type.OBJECT,
  properties: {
    usageId: { type: Type.STRING },
    tweetId: { type: Type.STRING, nullable: true },
    mediaIndex: { type: Type.INTEGER },
    mediaKind: { type: Type.STRING, enum: ["image", "video", "video_hls", "video_blob"] },
    status: { type: Type.STRING, enum: ["pending", "complete"] },
    has_celebrity: { type: Type.BOOLEAN, nullable: true },
    has_human_face: { type: Type.BOOLEAN, nullable: true },
    features_female: { type: Type.BOOLEAN, nullable: true },
    features_male: { type: Type.BOOLEAN, nullable: true },
    has_screenshot_ui: { type: Type.BOOLEAN, nullable: true },
    has_text_overlay: { type: Type.BOOLEAN, nullable: true },
    has_chart_or_graph: { type: Type.BOOLEAN, nullable: true },
    has_logo_or_watermark: { type: Type.BOOLEAN, nullable: true },
    caption_brief: { type: Type.STRING, nullable: true },
    scene_description: { type: Type.STRING, nullable: true },
    ocr_text: { type: Type.STRING, nullable: true },
    primary_subjects: { type: Type.ARRAY, items: { type: Type.STRING } },
    secondary_subjects: { type: Type.ARRAY, items: { type: Type.STRING } },
    visible_objects: { type: Type.ARRAY, items: { type: Type.STRING } },
    setting_context: { type: Type.STRING, nullable: true },
    action_or_event: { type: Type.STRING, nullable: true },
    video_music: { type: Type.STRING, nullable: true },
    video_sound: { type: Type.STRING, nullable: true },
    video_dialogue: { type: Type.STRING, nullable: true },
    video_action: { type: Type.STRING, nullable: true },
    primary_emotion: { type: Type.STRING, nullable: true },
    emotional_tone: { type: Type.STRING, nullable: true },
    conveys: { type: Type.STRING, nullable: true },
    user_intent: { type: Type.STRING, nullable: true },
    rhetorical_role: { type: Type.STRING, nullable: true },
    text_media_relationship: { type: Type.STRING, nullable: true },
    metaphor: { type: Type.STRING, nullable: true },
    humor_mechanism: { type: Type.STRING, nullable: true },
    cultural_reference: { type: Type.STRING, nullable: true },
    reference_entity: { type: Type.STRING, nullable: true },
    reference_source: { type: Type.STRING, nullable: true },
    reference_plot_context: { type: Type.STRING, nullable: true },
    analogy_target: { type: Type.STRING, nullable: true },
    analogy_scope: { type: Type.STRING, nullable: true },
    meme_format: { type: Type.STRING, nullable: true },
    persuasion_strategy: { type: Type.STRING, nullable: true },
    brand_signals: { type: Type.ARRAY, items: { type: Type.STRING } },
    trend_signal: { type: Type.STRING, nullable: true },
    reuse_pattern: { type: Type.STRING, nullable: true },
    why_it_works: { type: Type.STRING, nullable: true },
    audience_takeaway: { type: Type.STRING, nullable: true },
    search_keywords: { type: Type.ARRAY, items: { type: Type.STRING } },
    confidence_notes: { type: Type.STRING, nullable: true },
    usage_notes: { type: Type.STRING, nullable: true }
  },
  required: [
    "usageId",
    "tweetId",
    "mediaIndex",
    "mediaKind",
    "status",
    "has_celebrity",
    "has_human_face",
    "features_female",
    "features_male",
    "has_screenshot_ui",
    "has_text_overlay",
    "has_chart_or_graph",
    "has_logo_or_watermark",
    "caption_brief",
    "scene_description",
    "ocr_text",
    "primary_subjects",
    "secondary_subjects",
    "visible_objects",
    "setting_context",
    "action_or_event",
    "video_music",
    "video_sound",
    "video_dialogue",
    "video_action",
    "primary_emotion",
    "emotional_tone",
    "conveys",
    "user_intent",
    "rhetorical_role",
    "text_media_relationship",
    "metaphor",
    "humor_mechanism",
    "cultural_reference",
    "reference_entity",
    "reference_source",
    "reference_plot_context",
    "analogy_target",
    "analogy_scope",
    "meme_format",
    "persuasion_strategy",
    "brand_signals",
    "trend_signal",
    "reuse_pattern",
    "why_it_works",
    "audience_takeaway",
    "search_keywords",
    "confidence_notes",
    "usage_notes"
  ]
} as const;

export function normalizeUsageAnalysis(analysis: UsageAnalysis): UsageAnalysis {
  return usageAnalysisSchema.parse({
    ...analysis,
    has_celebrity: analysis.has_celebrity ?? null,
    has_human_face: analysis.has_human_face ?? null,
    features_female: analysis.features_female ?? null,
    features_male: analysis.features_male ?? null,
    has_screenshot_ui: analysis.has_screenshot_ui ?? null,
    has_text_overlay: analysis.has_text_overlay ?? null,
    has_chart_or_graph: analysis.has_chart_or_graph ?? null,
    has_logo_or_watermark: analysis.has_logo_or_watermark ?? null,
    caption_brief: analysis.caption_brief ?? null,
    scene_description: analysis.scene_description ?? null,
    ocr_text: analysis.ocr_text ?? null,
    setting_context: analysis.setting_context ?? null,
    action_or_event: analysis.action_or_event ?? null,
    video_music: analysis.video_music ?? null,
    video_sound: analysis.video_sound ?? null,
    video_dialogue: analysis.video_dialogue ?? null,
    video_action: analysis.video_action ?? null,
    primary_emotion: analysis.primary_emotion ?? null,
    emotional_tone: analysis.emotional_tone ?? null,
    conveys: analysis.conveys ?? null,
    user_intent: analysis.user_intent ?? null,
    rhetorical_role: analysis.rhetorical_role ?? null,
    text_media_relationship: analysis.text_media_relationship ?? null,
    metaphor: analysis.metaphor ?? null,
    humor_mechanism: analysis.humor_mechanism ?? null,
    cultural_reference: analysis.cultural_reference ?? null,
    reference_entity: analysis.reference_entity ?? null,
    reference_source: analysis.reference_source ?? null,
    reference_plot_context: analysis.reference_plot_context ?? null,
    analogy_target: analysis.analogy_target ?? null,
    analogy_scope: analysis.analogy_scope ?? null,
    meme_format: analysis.meme_format ?? null,
    persuasion_strategy: analysis.persuasion_strategy ?? null,
    trend_signal: analysis.trend_signal ?? null,
    reuse_pattern: analysis.reuse_pattern ?? null,
    why_it_works: analysis.why_it_works ?? null,
    audience_takeaway: analysis.audience_takeaway ?? null,
    confidence_notes: analysis.confidence_notes ?? null,
    usage_notes: analysis.usage_notes ?? null,
    primary_subjects: analysis.primary_subjects ?? [],
    secondary_subjects: analysis.secondary_subjects ?? [],
    visible_objects: analysis.visible_objects ?? [],
    brand_signals: analysis.brand_signals ?? [],
    search_keywords: analysis.search_keywords ?? []
  });
}
